apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
  namespace: {{.Values.namespace}}
  labels: {{ include "fastapi.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    workload.user.cattle.io/workloadselector: {{ .Values.selector }} 
  ports:
    - name: {{ .Values.service.name }}
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetport}}
      protocol: TCP
