name: CI Docker and Kubernets
on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image #and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: self-hosted

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image and push to Github Packages
        uses:  docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Check, create, deploy Helm to Kubernetes
        run: |
            helm install fast-api api/ 
            helm upgrade api api/

      #- name: Deploy to Kubernetes
        #run: kubectl apply -f api/deploy.yaml --validate=false

